# Hypotension Prediction Task Configuration

task:
  name: "hypotension_prediction"
  type: "classification"
  num_classes: 2
  
  # Prediction windows (minutes before hypotension onset)
  prediction_windows: [5, 10, 15]
  
  # Clinical definition
  map_threshold_mmhg: 65.0
  sustained_duration_s: 60.0
  
  # Data parameters
  sampling_rate: 2.0  # Hz (2-second intervals for MAP)
  window_size_s: 300.0  # 5-minute input window
  
  # Required signals
  required_channels:
    - "Solar8000/ART_MBP"  # Mean arterial pressure (primary)
    - "SNUADC/ART"         # Arterial waveform (fallback)
  
  # Quality control
  quality:
    min_sqi: 0.8
    min_valid_ratio: 0.90
    check_artifacts: true
    
  # Feature extraction
  features:
    enabled: true
    extract_trend: true
    extract_variability: true
    extract_clinical: true
    window_history_min: 5  # Minutes of history for features

# Model configuration for this task
model:
  # Foundation model mode
  freeze_encoder: true
  head_type: "mlp"
  head_config:
    hidden_dims: [256, 128]
    dropout: 0.3
    activation: "gelu"
  
  # Fine-tuning mode (optional)
  # freeze_encoder: false
  # unfreeze_last_n_blocks: 2
  # lora:
  #   enabled: true
  #   r: 8
  #   alpha: 16

# Training parameters
training:
  batch_size: 64
  learning_rate: 1e-4
  epochs: 50
  early_stopping_patience: 10
  
  # Class imbalance handling
  use_class_weights: true
  focal_loss:
    enabled: true
    alpha: 0.25
    gamma: 2.0
  
  # Data augmentation
  augmentation:
    enabled: true
    methods:
      - "amplitude_scale"
      - "gaussian_noise"
      - "time_warp"
    probabilities: [0.5, 0.3, 0.2]

# Evaluation
evaluation:
  primary_metric: "auprc"  # Preferred for imbalanced data
  secondary_metrics:
    - "auroc"
    - "f1"
    - "accuracy"
  
  # Threshold optimization
  optimize_threshold: true
  threshold_metric: "f1"  # Optimize for F1 score
  
  # Clinical thresholds
  target_auroc: 0.90
  target_auprc: 0.70
  minimum_sensitivity: 0.80
  maximum_false_positive_rate: 0.20

# Benchmarks for comparison
benchmarks:
  - paper: "STEP-OP (Choe et al.)"
    year: 2021
    dataset: "VitalDB"
    n_patients: 18813
    metrics:
      auroc: 0.900
      auprc: 0.716
    notes: "Most rigorous label generation"
  
  - paper: "Jo et al."
    year: 2022
    dataset: "VitalDB"
    n_patients: 5230
    metrics:
      auroc: 0.935
      auprc: 0.882
    notes: "ABP + EEG multimodal"
  
  - paper: "Jeong et al."
    year: 2024
    dataset: "VitalDB"
    n_patients: 3200
    metrics:
      auroc: 0.917
      auprc: 0.850
    notes: "Non-invasive (no arterial line)"
