# Fixed Channel Configuration for VitalDB Biosignals

ECG:
  vitaldb_track: "ECG_II"
  sampling_rate: 125
  original_rate: 500
  filter:
    type: "butter"  # FIXED: was "butterworth"
    order: 4
    lowcut: 0.5     # FIXED: renamed from low_freq
    highcut: 40     # FIXED: renamed from high_freq
  quality_metrics:
    - "sqi"
    - "bsqi"
  min_quality: 0.9
  type: "ecg"       # Added signal type
    
PPG:
  vitaldb_track: "PLETH"
  sampling_rate: 125
  original_rate: 100
  filter:
    type: "cheby2"   # Already correct
    order: 4
    lowcut: 0.4      # FIXED: renamed from low_freq
    highcut: 7       # FIXED: renamed from high_freq
    ripple_db: 20
  quality_metrics:
    - "ssqi"
    - "psqi"
  min_quality: 0.8
  type: "ppg"        # Added signal type
    
ABP:
  vitaldb_track: "ABP"
  sampling_rate: 125
  original_rate: 100
  filter:
    type: "butter"   # FIXED: was "butterworth"
    order: 4
    lowcut: 0.5      # FIXED: renamed from low_freq
    highcut: 20      # FIXED: renamed from high_freq
  quality_metrics:
    - "template_match"
  min_quality: 0.85
  type: "abp"        # Added signal type
