# FastTrack Configuration for CPU with Real TTM
# Realistic settings for ~1-3 hour training

data:
  data_root: data/processed/VitalDB
  signal_types: ['ECG_II', 'PLETH', 'ABP']
  target_signals: ['ECG_II', 'PLETH', 'ABP']
  sequence_length: 1250  # 10 seconds at 125Hz
  sampling_rate: 125
  stride: 625  # 50% overlap
  normalization: standardize
  augmentation:
    enabled: false  # Disable for speed on CPU
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  max_cases: 50  # Start with 50 cases for FastTrack

model:
  variant: ibm-granite/granite-timeseries-ttm-r1
  task: classification
  num_classes: 2
  input_channels: 3
  context_length: 512
  prediction_length: 96
  freeze_encoder: true  # KEEP FROZEN for fast training
  head_type: linear  # Simple linear head for speed
  head_config:
    dropout: 0.2
  decoder_mode: mix_channel
  lora:
    enabled: false  # Disable LoRA for simplicity

training:
  batch_size: 8  # Small batch for CPU
  learning_rate: 1e-3  # Higher LR since backbone is frozen
  weight_decay: 1e-4
  num_epochs: 20  # Quick training
  device: cpu
  num_workers: 2  # Limited workers for CPU
  
  optimizer: adam
  scheduler: cosine
  warmup_epochs: 2
  
  gradient_clip: 1.0
  mixed_precision: false  # No AMP on CPU
  
  log_interval: 10
  save_interval: 5
  eval_interval: 1
  
  early_stopping_patience: 5
  early_stopping_min_delta: 0.001
  
  model_dir: checkpoints/fasttrack_ttm
  log_dir: logs/fasttrack_ttm
  
  # CPU-specific optimizations
  pin_memory: false
  persistent_workers: false
  prefetch_factor: 2

experiment:
  name: fasttrack_ttm_frozen
  description: "FastTrack with real TTM, frozen backbone, 50 cases"
  tags: ["ttm", "frozen", "cpu", "fasttrack"]
  seed: 42
  deterministic: true
  benchmark: false  # Disable cudnn benchmark on CPU
