# Window Configuration for Biosignal Processing

# Window extraction parameters
window:
  size_seconds: 10.0        # 10-second windows (1250 samples at 125 Hz)
  step_seconds: 10.0        # Non-overlapping during SSL pretrain
