# Window Configuration for Biosignal Processing
# Aligned with TTM-Enhanced architecture requirements

# Window extraction parameters
window:
  size_seconds: 4.096       # IBM TTM-Enhanced: 512 samples at 125 Hz (8 patches @ 64 samples/patch)
  step_seconds: 4.096       # Non-overlapping during SSL pretrain

# Supervised task configuration (for fine-tuning)
# Article recommends 50% overlap for supervised tasks
supervised:
  size_seconds: 4.096       # IBM TTM-Enhanced compatible window size (512 samples)
  step_seconds: 2.048       # 50% overlap (2.048s step) for more training samples
