# Window Configuration for Biosignal Processing

# Window extraction parameters
window:
  size_seconds: 10.0        # 10-second windows (standard for HRV)
  step_seconds: 10.0        # Non-overlapping by default
  min_duration: 10.0        # Minimum valid signal duration
  
  # For training vs inference
  training:
    overlap: 0.0           # No overlap during training
    augment: false         # Data augmentation
    
  inference:
    overlap: 0.5           # 50% overlap for better temporal resolution
    voting: "soft"         # soft, hard, or weighted
    context_extension: 2.0  # Extra seconds for context

# Quality control thresholds
quality:
  min_cycles: 3            # Minimum cardiac cycles per window
  
  # Signal-specific quality
  ecg:
    min_sqi: 0.9           # Minimum Signal Quality Index
    max_noise_ratio: 0.1   # Maximum noise-to-signal ratio
    check_flatline: true   # Detect flat signals
    check_saturation: true # Detect clipped signals
    
  ppg:
    min_ssqi: 0.8          # Minimum Skewness SQI
    min_perfusion: 0.01    # Minimum perfusion index
    check_artifacts: true   # Motion artifact detection
    
  abp:
    min_pulse_pressure: 20  # Minimum pulse pressure (mmHg)
    max_pulse_pressure: 200 # Maximum pulse pressure
    check_physiological: true # Physiological range checks

# Peak detection parameters
peak_detection:
  ecg:
    method: "neurokit2"    # or "pan_tompkins", "hamilton"
    correct_artifacts: true
    
  ppg:
    method: "adaptive"     # Adaptive threshold
    smooth_window: 0.2     # Smoothing window (seconds)
    
  abp:
    method: "derivative"   # First derivative method
    min_prominence: 5      # Minimum peak prominence (mmHg)

# Normalization strategy
normalization:
  method: "zscore"         # zscore, minmax, robust
  
  # Per-channel normalization
  per_channel: true
  
  # Population statistics (computed from training set)
  use_population_stats: true
  stats_file: "configs/population_stats.json"
  
  # Clipping outliers
  clip_values: true
  clip_range: [-5, 5]     # In standard deviations

# Artifact handling
artifacts:
  detection:
    - "flatline"          # Constant signal
    - "saturation"        # Clipped signal
    - "noise_burst"       # Sudden noise
    - "baseline_shift"    # Sudden baseline change
    
  handling: "exclude"      # exclude, interpolate, or mark
  
  # Artifact-specific thresholds
  flatline_seconds: 1.0
  saturation_threshold: 0.95  # Fraction of range
  noise_threshold: 3.0         # Standard deviations

# Data validation
validation:
  check_nan: true
  check_inf: true
  check_range: true
  
  # Physiological ranges
  ranges:
    ecg: [-5, 5]          # mV
    ppg: [0, 1]           # Normalized
    abp: [0, 300]         # mmHg
    
# FastTrack mode settings
fasttrack:
  enabled: false           # Set via CLI flag
  max_windows_per_case: 10 # Limit windows per patient
  skip_quality_checks: false # Still do basic QC
  simplified_preprocessing: true
